### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by salmonmolon** [ShimmyMySherbet/MusixDownloader#1]
Is support for Linux planned? As of right now I can't compile because it uses .NET Framework. Is use of .NET Core planned in the future? Thanks for your attention.

**Comment by ShimmyMySherbet** [comment]
Sorry for the late reply, I was on holidays.
The way Musix is structured, the core logic/downloader is encompassed in Musix.Core, which is .NET Standard. This means the Musix Clients are just built around Musix.Core. 
Support for Linux is planned, however, it would likely just be a command-line utility.

**Comment by salmonmolon** [comment]
Thanks a lot using a cli is still very cool. Hope your project gets noticed by more people!

**Comment by Donokami** [comment]
Is it possible to re-open the issue? I would be very interested for a Linux version!
